export {default as SegmentedDialog } from "./SegmentedDialog";
export {default as ConfirmDialog } from "./ConfirmDialog";
export type {DialogBodyProps} from "./Body";
export type {DialogCloseProps} from "./Close";
export type {DialogCloseIconProps} from "./CloseIcon";
export type {DialogContentProps} from "./Content";
export type {DialogDescriptionProps} from "./Description";
export type {ConfirmDialogProps} from "./ConfirmDialog";
export type {DialogFooterProps} from "./Footer"; 
export type {DialogHeaderProps} from "./Header";
export type {DialogOverlayProps} from "./Overlay";
export type {DialogPortalProps} from "./Portal";
export type {DialogSegmentedContentProps} from "./SegmentedContent";
export type {DialogTitleProps} from "./Title";
export type {DialogTriggerProps} from "./Trigger";